syntax = "proto3";

package sso.v1;

option go_package = "github.com/EliasBlind/EduFlow/pkg/protos/gen/sso/v1;ssov1";

import "google/protobuf/empty.proto";

// Авторизация пользователей
service Auth {
  // Регистрация нового пользователя
  rpc Register(RegisterRequest) returns (RegisterResponse);

  // Верефикация почты (двухфакторная аунтетификация)
  rpc VerifyEmail(VerifyRequest) returns (TokenPair);

  // При логине выдаем сразу два токена
  rpc Login(LoginRequest) returns (TokenPair);

  // Разлогинится
  rpc Logout(LogoutRequest) returns (LogoutResponse);

  // Для обновления передаем Refresh-токен
  rpc RefreshToken(RefreshRequest) returns (TokenPair);

  // Получение информации обовсех юзерах.
  rpc ListUsers(TokenRequest) returns (ListUsersResponse);

  rpc SetRole(SetRoleRequest) returns (google.protobuf.Empty);
}

message RegisterRequest {
  string email    = 1;
  string login    = 2;
  string password = 3;
  int32  app_id   = 4;
}

message RegisterResponse {}

message VerifyRequest {
  string email = 1;
  string code  = 2;
}

message LoginRequest {
  string login    = 1;
  string password = 2;
  int32  app_id   = 3;
}

message RefreshRequest {
  string refresh_token = 1;
  int32  app_id        = 2;
}

message TokenPair {
  string access_token  = 1;
  string refresh_token = 2; // uuid
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message TokenRequest {
  // jwt токен
  string token = 1;
}

message User {
  string id = 1; // uuid
  string login = 2;
  string email = 3;
  string role = 4;
}

message ListUsersResponse {
  uint32           total_count = 1;
  repeated User users = 2;
}

message SetRoleRequest {
  // jwt токен
  string token = 1;
  string user_id = 2;
  string role = 3;
}
